### ISSUE TITLE
GEMM function for ARM device

### ISSUE THREAD

**Issue by shalom-aviv** [james34602/SpleeterRT#6]
```
I haven't investigated the GEMM function for ARM device, if anyone finds good implementation, perhaps make a pull request to gemm.c.
```
May be this [link](https://github.com/ARM-software/ComputeLibrary) will helpfull

<img width="831" alt="Screenshot 2021-11-07 at 13 09 44" src="https://user-images.githubusercontent.com/78256107/140640757-60b67578-d099-4664-aec9-f459d2783eeb.png">

**Comment by james34602** [comment]
OK, thank you.
The project is not active anymore and the code have other use, so do not expect there's any dramatic changes in the future.
